language: node_js

node_js:
  - "14"
  - "12"
  - "10"
  - "9"
  - "8"
  - "6"

# before_install:
#   - curl -L https://unpkg.com/@pnpm/self-installer | node
# install:
#   - pnpm install

script:
  - npm run lint-ci
  - npm run test-ci
  - node_version=$(node -v); if [ ${node_version:1:1} > 9 ]; then npm run test-types; else echo "Skip TS tests"; fi

notifications:
  email:
    on_success: never
    on_failure: always
