name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '6', '8', '9', '10', '12', '14' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: npm install
      env:
        NODE_ENV: development
    - name: Lint-CI
      run: npm run lint-ci
    - name: Test-CI
      run: npm run test-ci

